cmake_minimum_required(VERSION 3.20)
foreach(required RENDERER SOURCE_DIR OUTPUT_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(READ "${SOURCE_DIR}/assets/renderjobs/05_cloud_determinism.renderjob" base)
string(JSON base SET "${base}" scene "\"${SOURCE_DIR}/assets/scenes/fixtures/23_ocean_clouds.myscene\"")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(run first repeat warmup temporal_first temporal_repeat)
    set(json "${base}")
    set(warmup 0)
    set(temporal OFF)
    if(run STREQUAL warmup)
        set(warmup 5)
    elseif(run MATCHES "^temporal_")
        set(warmup 5)
        set(temporal ON)
        string(JSON json SET "${json}" raster determinism false)
        string(JSON json SET "${json}" raster temporalAccumulation true)
    endif()
    string(JSON json SET "${json}" raster warmupFrames ${warmup})
    set(job "${OUTPUT_DIR}/${run}.renderjob")
    file(WRITE "${job}" "${json}")
    set(directory "${OUTPUT_DIR}/${run}")
    file(MAKE_DIRECTORY "${directory}")
    foreach(frame RANGE 0 2)
        set(stem "${directory}/frame_000${frame}")
        file(REMOVE "${stem}.png" "${stem}-report.json" "${stem}.png.partial.png" "${stem}-report.json.partial")
    endforeach()
    execute_process(COMMAND "${RENDERER}" raster-sequence "${job}"
        --output "${directory}/frame_{frame:04}"
        WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE result TIMEOUT 180)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cloud deterministic Render Job ${run} failed: ${result}")
    endif()
    foreach(frame RANGE 0 2)
        set(stem "${directory}/frame_000${frame}")
        if(NOT EXISTS "${stem}.png" OR NOT EXISTS "${stem}-report.json")
            message(FATAL_ERROR "Missing raster image/report pair")
        endif()
        file(READ "${stem}-report.json" report)
        string(JSON density_source GET "${report}" cloud densitySource)
        string(JSON noise_fingerprint GET "${report}" cloud offlineAssets 0 fingerprint)
        string(JSON noise_resource GET "${report}" cloud offlineAssets 0 resource)
        if(NOT density_source STREQUAL "offline-rgba16-shared-field"
            OR NOT noise_fingerprint STREQUAL "4464bd382daa06f7"
            OR NOT noise_resource STREQUAL "assets/clouds/noise-v1-64-period4.cloudnoise")
            message(FATAL_ERROR "Raster capture omitted the actual offline noise identity")
        endif()
        string(JSON lut GET "${report}" cloud offlineAssets 1 fingerprint)
        string(JSON transport GET "${report}" cloud lightingTransportSource)
        string(JSON complete GET "${report}" inputManifest complete)
        string(JSON files GET "${report}" inputManifest files)
        if(NOT lut STREQUAL "36a2741b31f43904" OR NOT transport STREQUAL "offline-beer-lambert-lut" OR NOT complete)
            message(FATAL_ERROR "Incomplete LUT/capture input contract")
        endif()
        foreach(dependency "MyRenderer.exe" "23_ocean_clouds.myscene" "cloud_layer.frag" "CloudField.h" "transport-v1.cloudlut" "noise-v1-64-period4.cloudnoise")
            string(FIND "${files}" "${dependency}" found)
            if(found LESS 0)
                message(FATAL_ERROR "Missing capture dependency: ${dependency}")
            endif()
        endforeach()
        string(JSON actual_warmup GET "${report}" capture warmupFrames)
        string(JSON actual_taa GET "${report}" capture effectiveTaa)
        string(JSON actual_cloud GET "${report}" capture effectiveCloudHistory)
        string(JSON actual_temporal GET "${report}" capture temporalAccumulation)
        string(JSON draws GET "${report}" capture renderedFramesAtFixedTime)
        math(EXPR expected_draws "${warmup}+1")
        if(NOT actual_warmup EQUAL warmup OR NOT draws EQUAL expected_draws
            OR NOT actual_taa STREQUAL temporal OR NOT actual_cloud STREQUAL temporal
            OR NOT actual_temporal STREQUAL temporal)
            message(FATAL_ERROR "Incorrect capture metadata for ${run}: ${report}")
        endif()
    endforeach()
endforeach()
foreach(frame RANGE 0 2)
    set(name "frame_000${frame}.png")
    file(SHA256 "${OUTPUT_DIR}/first/${name}" first)
    file(SHA256 "${OUTPUT_DIR}/repeat/${name}" repeat)
    file(SHA256 "${OUTPUT_DIR}/warmup/${name}" warmup)
    file(SHA256 "${OUTPUT_DIR}/temporal_first/${name}" temporal_first)
    file(SHA256 "${OUTPUT_DIR}/temporal_repeat/${name}" temporal_repeat)
    if(NOT first STREQUAL repeat OR NOT first STREQUAL warmup OR NOT temporal_first STREQUAL temporal_repeat)
        message(FATAL_ERROR "Cloud frame ${frame} is not repeatable under the declared capture policy")
    endif()
endforeach()
file(SHA256 "${OUTPUT_DIR}/first/frame_0000.png" before)
file(SHA256 "${OUTPUT_DIR}/temporal_first/frame_0000.png" accumulated)
if(before STREQUAL accumulated)
    message(FATAL_ERROR "Temporal capture must exercise a different sampling/history path")
endif()
file(SHA256 "${OUTPUT_DIR}/first/frame_0002.png" after)
if(before STREQUAL after)
    message(FATAL_ERROR "Fixed-time warmup must not freeze the requested output timeline")
endif()
message(STATUS "Cloud determinism acceptance: PASS (15 PNG/report pairs, warmup invariance, repeated temporal captures)")
