cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED GENERATOR OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "GENERATOR and OUTPUT_DIR required")
endif()
string(RANDOM LENGTH 8 ALPHABET 0123456789abcdef run)
set(directory "${OUTPUT_DIR}/repeat-${run}")
file(MAKE_DIRECTORY "${directory}")
foreach(name first second)
    execute_process(COMMAND "${GENERATOR}" generate "${directory}/${name}.cloudnoise" 64 4
        RESULT_VARIABLE result OUTPUT_VARIABLE fingerprint ERROR_VARIABLE error TIMEOUT 90)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Noise generation failed: ${error}")
    endif()
    execute_process(COMMAND "${GENERATOR}" verify "${directory}/${name}.cloudnoise"
        RESULT_VARIABLE result OUTPUT_VARIABLE verified ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT "${verified}" STREQUAL "${fingerprint}")
        message(FATAL_ERROR "Noise verification failed: ${error}")
    endif()
endforeach()
file(SHA256 "${directory}/first.cloudnoise" first)
file(SHA256 "${directory}/second.cloudnoise" second)
file(SHA256 "${directory}/first.cloudnoise.json" first_manifest)
file(SHA256 "${directory}/second.cloudnoise.json" second_manifest)
if(NOT first STREQUAL second OR NOT first_manifest STREQUAL second_manifest)
    message(FATAL_ERROR "Repeated noise assets/manifests differ")
endif()
# Cross-check independently generated file against the asset uploaded by the GPU test.
file(SHA256 "${OUTPUT_DIR}/64-period-4.cloudnoise" gpu_asset)
if(NOT gpu_asset STREQUAL first)
    message(FATAL_ERROR "Tool and GPU consumer used different assets")
endif()
if(DEFINED CANONICAL_ASSET)
    execute_process(COMMAND "${GENERATOR}" verify "${CANONICAL_ASSET}" RESULT_VARIABLE canonical_valid)
    file(SHA256 "${CANONICAL_ASSET}" canonical_sha)
    if(NOT canonical_valid EQUAL 0 OR NOT canonical_sha STREQUAL first)
        message(FATAL_ERROR "Generator no longer reproduces the versioned noise input")
    endif()
endif()
execute_process(COMMAND "${GENERATOR}" generate "${directory}/first.cloudnoise" 64 4 RESULT_VARIABLE overwrite)
if(overwrite EQUAL 0)
    message(FATAL_ERROR "Existing noise asset was overwritten")
endif()
execute_process(COMMAND "${GENERATOR}" preview "${directory}/first.cloudnoise" "${directory}/channels.ppm"
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Noise preview failed")
endif()
file(WRITE "${OUTPUT_DIR}/repeat-result.json" "{\"sha256\":\"${first}\",\"manifestSha256\":\"${first_manifest}\",\"preview\":\"repeat-${run}/channels.ppm\"}\n")
message(STATUS "Offline asset and manifest repeat exactly; SHA256 ${first}")
