cmake_minimum_required(VERSION 3.20)
foreach(required RENDERER COMPARATOR SOURCE_DIR OUTPUT_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} required")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(scene "${SOURCE_DIR}/assets/scenes/fixtures/28_native_ocean_clouds.myscene")
file(SHA256 "${scene}" scene_hash)
function(capture name frame tier width height)
    if(tier STREQUAL low)
        set(water_quality 0)
    else()
        set(water_quality 1)
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        MYRENDERER_BENCHMARK_FRAMES=240 MYRENDERER_BENCHMARK_WARMUP=64
        "MYRENDERER_BENCHMARK_OUTPUT=${OUTPUT_DIR}/${name}.json"
        "MYRENDERER_SCREENSHOT=${OUTPUT_DIR}/${name}.png"
        MYRENDERER_SCREENSHOT_WARMUP=64
        "MYRENDERER_RENDER_WIDTH=${width}" "MYRENDERER_RENDER_HEIGHT=${height}"
        "MYRENDERER_TIMELINE_FRAME=${frame}" MYRENDERER_ANIMATION_FRAME_STEP=0
        "MYRENDERER_CLOUD_TIER=${tier}" "MYRENDERER_WATER_QUALITY=${water_quality}"
        MYRENDERER_CLOUD_HALF_RESOLUTION=1 MYRENDERER_CLOUD_TEMPORAL=1
        MYRENDERER_HIDE_SELECTION_OUTLINE=1
        "MYRENDERER_RENDER_QUEUE_STATE=${OUTPUT_DIR}/queue.json"
        "${RENDERER}" "${scene}"
        WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 180)
    file(WRITE "${OUTPUT_DIR}/${name}.log" "${output}\n${errors}")
    if(NOT result EQUAL 0 OR NOT EXISTS "${OUTPUT_DIR}/${name}.png"
        OR NOT EXISTS "${OUTPUT_DIR}/${name}.json")
        message(FATAL_ERROR "Hero capture failed: ${name}/${result}")
    endif()
    file(READ "${OUTPUT_DIR}/${name}.json" report)
    string(JSON samples GET "${report}" gpuFrameMeasurements)
    string(JSON actual_width GET "${report}" width)
    string(JSON actual_height GET "${report}" height)
    string(JSON actual_time GET "${report}" animationTimeSeconds)
    string(JSON fixed GET "${report}" animationTimeFixed)
    if(samples LESS 120 OR NOT actual_width EQUAL width OR NOT actual_height EQUAL height OR NOT fixed)
        message(FATAL_ERROR "Invalid measured input/samples: ${name}")
    endif()
    if(tier STREQUAL low)
        set(frame_budget 8.33)
        set(cloud_budget 4.0)
        set(shadow_budget 0.75)
        set(water_budget 0.5)
    else()
        set(frame_budget 16.67)
        set(cloud_budget 10.0)
        set(shadow_budget 1.5)
        set(water_budget 0.75)
    endif()
    foreach(field cpuFrameP95Ms gpuFrameP95Ms)
        string(JSON measured GET "${report}" "${field}")
        if(measured GREATER frame_budget)
            set_property(GLOBAL APPEND PROPERTY M2A_BUDGET_FAILURES "${name}/${field}: ${measured} > ${frame_budget} ms")
        endif()
    endforeach()
    # Both CPU submission and asynchronous GPU costs must be observable for the
    # three passes owning the combined native scene. No image baseline is updated.
    foreach(pass "Cloud volume march" "Cloud sun transmission" "Forward transparent / refractive scene")
        if(frame EQUAL 23 AND pass STREQUAL "Cloud sun transmission")
            continue() # Solar shadow map is intentionally absent after sunset.
        endif()
        foreach(domain cpuPasses gpuPasses)
            string(JSON count GET "${report}" "${domain}" "${pass}" measurements)
            string(JSON p95 GET "${report}" "${domain}" "${pass}" p95Ms)
            if(count LESS 120 OR p95 LESS_EQUAL 0)
                message(FATAL_ERROR "Missing ${domain}/${pass} samples: ${name}")
            endif()
            if(domain STREQUAL gpuPasses)
                if(pass STREQUAL "Cloud volume march")
                    set(pass_budget ${cloud_budget})
                elseif(pass STREQUAL "Cloud sun transmission")
                    set(pass_budget ${shadow_budget})
                else()
                    set(pass_budget ${water_budget})
                endif()
                if(p95 GREATER pass_budget)
                    set_property(GLOBAL APPEND PROPERTY M2A_BUDGET_FAILURES "${name}/${pass}: ${p95} > ${pass_budget} ms")
                endif()
            endif()
        endforeach()
    endforeach()
    string(JSON last_frame GET "${report}" moduleLastFrame)
    string(JSON fps GET "${report}" moduleFps)
    string(JSON module_id GET "${report}" moduleId)
    string(JSON seed GET "${report}" moduleSeed)
    string(JSON build_id GET "${report}" moduleBuildId)
    if(frame EQUAL 0)
        set(expected_time 0.0)
    elseif(frame EQUAL 15)
        set(expected_time 0.625)
    else()
        set(expected_time 0.958333)
    endif()
    if(NOT last_frame EQUAL frame OR NOT fps EQUAL 24
        OR NOT module_id STREQUAL "myrenderer.core.coastal-sequence"
        OR NOT seed EQUAL 20261006 OR build_id STREQUAL ""
        OR NOT actual_time EQUAL expected_time)
        message(FATAL_ERROR "Hero timeline input mismatch: ${name}")
    endif()
endfunction()
foreach(tier low high)
    if(tier STREQUAL low)
        set(width 960)
        set(height 540)
    else()
        set(width 1280)
        set(height 720)
    endif()
    capture(noon-${tier} 0 ${tier} ${width} ${height})
    capture(sunset-${tier} 15 ${tier} ${width} ${height})
    capture(night-${tier} 23 ${tier} ${width} ${height})
endforeach()
capture(noon-high-repeat 0 high 1280 720)
execute_process(COMMAND "${COMPARATOR}" "${OUTPUT_DIR}/noon-high.png"
    "${OUTPUT_DIR}/noon-high-repeat.png" 0.00001 0
    RESULT_VARIABLE repeat_result)
if(NOT repeat_result EQUAL 0)
    message(FATAL_ERROR "Hero fixed inputs did not repeat")
endif()
file(SHA256 "${scene}" final_scene_hash)
if(NOT scene_hash STREQUAL final_scene_hash)
    message(FATAL_ERROR "Hero scene changed during capture")
endif()
file(WRITE "${OUTPUT_DIR}/inputs.json"
    "{\"scene\":\"assets/scenes/fixtures/28_native_ocean_clouds.myscene\",\"sha256\":\"${scene_hash}\",\"moduleId\":\"myrenderer.core.coastal-sequence\",\"moduleApiVersion\":1,\"timeStepSeconds\":0.041666666666666664,\"fps\":24,\"seed\":20261006,\"frames\":[0,15,23],\"warmupFrames\":64,\"measurementFrames\":240,\"low\":[960,540],\"high\":[1280,720]}\n")
file(WRITE "${OUTPUT_DIR}/functional.txt" "PASS: 3 moods, 2 tiers, CPU/GPU pass samples and deterministic repeat\n")
get_property(budget_failures GLOBAL PROPERTY M2A_BUDGET_FAILURES)
if(budget_failures)
    list(JOIN budget_failures "\n" failure_text)
    file(WRITE "${OUTPUT_DIR}/acceptance.txt" "FAIL: performance budgets\n${failure_text}\n")
    message(FATAL_ERROR "M2-A performance budgets unmet (unchanged thresholds):\n${failure_text}")
endif()
file(WRITE "${OUTPUT_DIR}/acceptance.txt" "PASS: functional and performance budgets\n")
