cmake_minimum_required(VERSION 3.20)
foreach(required RENDERER COMPARATOR CALIBRATION FIELD MARCH TEMPORAL SOURCE_DIR OUTPUT_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} required")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT_DIR}/cloud-acceptance.txt" "INCOMPLETE: validation running\n")
# Reuse the frozen camera/quality/time and original budgets; keep M2-A evidence.
include("${SOURCE_DIR}/tools/M2AHeroAcceptance.cmake")
function(check name)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${SOURCE_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 180)
    file(WRITE "${OUTPUT_DIR}/${name}.log" "${output}\n${errors}")
    message(STATUS "${name}: ${output}")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${name} failed: ${result}/${errors}")
    endif()
endfunction()
check(hero-shape "${CALIBRATION}" --hero
    "${SOURCE_DIR}/assets/scenes/fixtures/28_native_ocean_clouds.myscene" "${OUTPUT_DIR}/shape")
check(perlin-field "${FIELD}" --shape)
foreach(source procedural offline)
    if(source STREQUAL offline)
        set(environment "${CMAKE_COMMAND}" -E env MYRENDERER_TEST_OFFLINE_NOISE=1)
    else()
        set(environment "${CMAKE_COMMAND}" -E env --unset=MYRENDERER_TEST_OFFLINE_NOISE)
    endif()
    foreach(sun 6 45 -12)
        check(march-${source}-${sun} ${environment} "${MARCH}" --height-lighting ${sun})
    endforeach()
endforeach()
check(temporal-height "${TEMPORAL}" "${OUTPUT_DIR}/temporal-height" --height-lighting)
check(temporal-legacy "${TEMPORAL}" "${OUTPUT_DIR}/temporal-legacy")
file(WRITE "${OUTPUT_DIR}/cloud-acceptance.txt"
    "PASS: unchanged Hero budgets; Low/High shape; shared Perlin field; procedural/offline sunrise/noon/night transport; static/moving history\n")
